//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren2_Gorodkov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tren2Entities1 : DbContext
    {
        public Tren2Entities1()
            : base("name=Tren2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agents> agents { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<LegalAddress> LegalAddress { get; set; }
        public virtual DbSet<LogoAgent> LogoAgent { get; set; }
        public virtual DbSet<products_short> products_short { get; set; }
        public virtual DbSet<productsale> productsale { get; set; }
        public virtual DbSet<TypeAgent> TypeAgent { get; set; }
    }
}
