//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren2_Gorodkov
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_short
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products_short()
        {
            this.productsale = new HashSet<productsale>();
        }
    
        public int id { get; set; }
        public string NameOfProduct { get; set; }
        public string ProductType { get; set; }
        public double VendorCode { get; set; }
        public double NumberOfPeopleForProduction { get; set; }
        public double ProductionShopNumber { get; set; }
        public double MinimumPriceForAgent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productsale> productsale { get; set; }
    }
}
