//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren2_Gorodkov
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsale
    {
        public int ID { get; set; }
        public int IdProduct { get; set; }
        public int IdAgent { get; set; }
        public System.DateTime ImplementationDate { get; set; }
        public double NumberOfProducts { get; set; }
    
        public virtual agents agents { get; set; }
        public virtual products_short products_short { get; set; }
    }
}
